Test.assert(Util.hexToDec("FF") == 255, "hexToDec uppercase")
Test.assert(Util.hexToDec("1a") == 26, "hexToDec lowercase")
Test.assert(Util.toHex(255) == "FF", "toHex")
Test.assert(Util.lpad("7", 3, "0") == "007", "lpad")
Test.assert(Util.reverse("abc") == "cba", "reverse")
Test.assert(Util.htmlEscape("<b>&\"'</b>") == "&lt;b&gt;&amp;&quot;&#x27;&lt;/b&gt;", "htmlEscape")
Test.assert(Util.urlEncode("a b&c=d?e") == "a+b\%26c\%3Dd\%3Fe", "urlEncode")
Test.assert(Util.urlDecode("a+b\%26c\%3Dd") == "a b&c=d", "urlDecode")
Test.assert(Util.secureEquals("abc", "abc"), "secureEquals equal")
Test.assert(!Util.secureEquals("abc", "abd"), "secureEquals different")
Test.assert(!Util.secureEquals(null, "abc"), "secureEquals null")
Test.assert(Util.toNum("42") == 42, "toNum string")
Test.assert(Util.toNum("nope") == 0, "toNum invalid")
Test.assert(Util.toNum(7) == 7, "toNum number")
var pos = Util.getPositionForIndex("line1\nline2", 7)
Test.assert(pos["line"] == 1, "getPositionForIndex line")
Test.assert(pos["column"] == 2, "getPositionForIndex column")
